/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JInternalFrame.java to edit this template
 */
package sistematransportadora.ui;

import java.util.ArrayList;
import javax.swing.ComboBoxModel;
import javax.swing.DefaultComboBoxModel;
import javax.swing.JOptionPane;
import sistematransportadora.modelo.Dimensoes;
import sistematransportadora.modelo.Embalagem;
import sistematransportadora.repositorio.EmbalagemRepositorio;
import sistematransportadora.servico.EmbalagemServico;
import sistematransportadora.servico.ProdutoServico;

/**
 *
 * @author evely
 */
public class CadastrarEmbalagem extends javax.swing.JInternalFrame {
    private ComboBoxModel tipoEmbalagemModelo;
    private ComboBoxModel ajustarProdutosModelo;
    private final EmbalagemServico embalagemServico;
    private final EmbalagemRepositorio embalagemRepositorio;
    private boolean caixaVazia;
    /**
     * Creates new form cadastrarEmbalagem
     */
    public CadastrarEmbalagem() {
        embalagemServico = new EmbalagemServico();
        embalagemRepositorio = new EmbalagemRepositorio();
        ajustarTipos();
        ajustarProdutos();
        initComponents();
        if(!caixaVazia){
            cbxProduto.setEnabled(true); 
        }
    }

    public ComboBoxModel getTipoEmbalagemModelo() {
        return tipoEmbalagemModelo;
    }

    public ComboBoxModel getAjustarProdutosModelo() {
        return ajustarProdutosModelo;
    }
    
    private void ajustarTipos(){
        var tiposEmbalagem = embalagemRepositorio.buscarTipos();
        var tiposNomes = new ArrayList<String>();
        
        for(var tipo : tiposEmbalagem){
            tiposNomes.add(tipo.nome());
        }
        
        tipoEmbalagemModelo = new DefaultComboBoxModel(tiposNomes.toArray());
    }
    
    private void ajustarProdutos(){
        var produtoServico = new ProdutoServico();
        var produtos = produtoServico.buscarTodos();
        var produtosNomes = new ArrayList<String>();
        
        for(var produto : produtos){
            System.out.println(produto.getNome());
            produtosNomes.add(produto.getNome());
        }
        caixaVazia = produtosNomes.isEmpty();
        ajustarProdutosModelo = new DefaultComboBoxModel(produtosNomes.toArray());
    }
    
    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        cbxProduto = new javax.swing.JComboBox<>();
        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        cbxTipos = new javax.swing.JComboBox<>();
        btnCadastrar = new javax.swing.JButton();
        pDimenssoes = new javax.swing.JPanel();
        jLabel3 = new javax.swing.JLabel();
        sAltura = new javax.swing.JSpinner();
        jLabel4 = new javax.swing.JLabel();
        sLargura = new javax.swing.JSpinner();
        jLabel5 = new javax.swing.JLabel();
        sComprimento = new javax.swing.JSpinner();
        jLabel6 = new javax.swing.JLabel();
        sPeso = new javax.swing.JSpinner();
        cbEmpilhavel = new javax.swing.JCheckBox();
        jLabel7 = new javax.swing.JLabel();
        jScrollPane1 = new javax.swing.JScrollPane();
        txtObs = new javax.swing.JTextArea();
        jLabel8 = new javax.swing.JLabel();
        txtID = new javax.swing.JTextField();

        setTitle("Cadastrar Embalagens");

        cbxProduto.setModel(getAjustarProdutosModelo());

        jLabel1.setText("Produto:");

        jLabel2.setText("Tipos:");

        cbxTipos.setModel(getTipoEmbalagemModelo());

        btnCadastrar.setText("Cadastrar");
        btnCadastrar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnCadastrarActionPerformed(evt);
            }
        });

        jLabel3.setText("Altura:");

        jLabel4.setText("Largura:");

        jLabel5.setText("Comprimento:");

        javax.swing.GroupLayout pDimenssoesLayout = new javax.swing.GroupLayout(pDimenssoes);
        pDimenssoes.setLayout(pDimenssoesLayout);
        pDimenssoesLayout.setHorizontalGroup(
            pDimenssoesLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(pDimenssoesLayout.createSequentialGroup()
                .addContainerGap()
                .addGroup(pDimenssoesLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(pDimenssoesLayout.createSequentialGroup()
                        .addComponent(jLabel5)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(sComprimento, javax.swing.GroupLayout.DEFAULT_SIZE, 115, Short.MAX_VALUE))
                    .addGroup(pDimenssoesLayout.createSequentialGroup()
                        .addComponent(jLabel3)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(sAltura))
                    .addGroup(pDimenssoesLayout.createSequentialGroup()
                        .addComponent(jLabel4)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(sLargura)))
                .addContainerGap())
        );
        pDimenssoesLayout.setVerticalGroup(
            pDimenssoesLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(pDimenssoesLayout.createSequentialGroup()
                .addContainerGap()
                .addGroup(pDimenssoesLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel3)
                    .addComponent(sAltura, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(pDimenssoesLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel4)
                    .addComponent(sLargura, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(pDimenssoesLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(sComprimento, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel5))
                .addContainerGap(10, Short.MAX_VALUE))
        );

        jLabel6.setText("Peso:");

        cbEmpilhavel.setText("Empilhável");

        jLabel7.setText("Observações:");

        txtObs.setColumns(20);
        txtObs.setRows(5);
        jScrollPane1.setViewportView(txtObs);

        jLabel8.setText("ID:");

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(24, 24, 24)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(jLabel7)
                        .addGap(18, 18, 18)
                        .addComponent(cbEmpilhavel)
                        .addGap(0, 0, Short.MAX_VALUE))
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                            .addComponent(jScrollPane1, javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(layout.createSequentialGroup()
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                    .addComponent(cbxTipos, javax.swing.GroupLayout.PREFERRED_SIZE, 100, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(jLabel2)
                                    .addComponent(jLabel1)
                                    .addComponent(cbxProduto, javax.swing.GroupLayout.PREFERRED_SIZE, 100, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addGroup(layout.createSequentialGroup()
                                        .addComponent(jLabel8)
                                        .addGap(3, 3, 3)
                                        .addComponent(txtID)))
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addGroup(layout.createSequentialGroup()
                                        .addGap(6, 6, 6)
                                        .addComponent(jLabel6)
                                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                        .addComponent(sPeso, javax.swing.GroupLayout.PREFERRED_SIZE, 80, javax.swing.GroupLayout.PREFERRED_SIZE))
                                    .addComponent(pDimenssoes, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))))
                        .addContainerGap(30, Short.MAX_VALUE))))
            .addGroup(layout.createSequentialGroup()
                .addGap(131, 131, 131)
                .addComponent(btnCadastrar, javax.swing.GroupLayout.PREFERRED_SIZE, 105, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 0, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(16, 16, 16)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabel8)
                            .addComponent(txtID, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(jLabel1)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(cbxProduto, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jLabel2))
                    .addComponent(pDimenssoes, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(sPeso, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jLabel6)
                            .addComponent(cbxTipos, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(50, 50, 50))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabel7)
                            .addComponent(cbEmpilhavel))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)))
                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(btnCadastrar, javax.swing.GroupLayout.PREFERRED_SIZE, 35, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(11, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void btnCadastrarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnCadastrarActionPerformed
       try {
            int id = Integer.parseInt(txtID.getText());
            var produtoServico = new ProdutoServico();
            var produto = produtoServico.buscarTodos()[cbxProduto.getSelectedIndex()];
            var empilhavel = cbEmpilhavel.isSelected();
            var tipo = embalagemRepositorio.buscarTipos()[cbxTipos.getSelectedIndex()];
            double altura = ((double)(int)sAltura.getValue());
            double largura = ((double)(int)sPeso.getValue());
            double comprimento = ((double)(int)sLargura.getValue());
            double peso = ((double)(int)sComprimento.getValue());      
            String obs = txtObs.getText();
            
            var dimensoes = new Dimensoes(altura, largura, comprimento);
            var embalagem = new Embalagem( id, tipo, produto, dimensoes, peso);
            embalagem.setEmpilhavel(empilhavel);
            embalagem.setObservacoes(obs);
           
            embalagemServico.cadastrarEmbalagem(embalagem);
       } catch(Exception e) {
            
            JOptionPane.showMessageDialog(null, e.getMessage(), "Erro!", JOptionPane.ERROR_MESSAGE);
            return;
       }
        JOptionPane.showMessageDialog(null, "Seu cadastro foi um sucesso!!!", "Sucesso!", JOptionPane.INFORMATION_MESSAGE);
        limpar();
                
    }//GEN-LAST:event_btnCadastrarActionPerformed
    private void limpar(){
        txtID.setText("");
        cbxProduto.setSelectedIndex(0);
        cbEmpilhavel.setSelected(false);
        sAltura.setValue(0);
        sLargura.setValue(0);
        sComprimento.setValue(0);
        sPeso.setValue(0);
        cbxTipos.setSelectedIndex(0);
        txtObs.setText("");

    } 

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnCadastrar;
    private javax.swing.JCheckBox cbEmpilhavel;
    private javax.swing.JComboBox<String> cbxProduto;
    private javax.swing.JComboBox<String> cbxTipos;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JPanel pDimenssoes;
    private javax.swing.JSpinner sAltura;
    private javax.swing.JSpinner sComprimento;
    private javax.swing.JSpinner sLargura;
    private javax.swing.JSpinner sPeso;
    private javax.swing.JTextField txtID;
    private javax.swing.JTextArea txtObs;
    // End of variables declaration//GEN-END:variables
}
