/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package sistematransportadora.ui;

/**
 *
 * @author evely
 */
public class TelaPrincipal extends javax.swing.JFrame {

    /**
     * Creates new form telaPrincipal
     */
    public TelaPrincipal() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        dpTelinha = new javax.swing.JDesktopPane();
        jMenuBar1 = new javax.swing.JMenuBar();
        jMenu1 = new javax.swing.JMenu();
        mnuVeiculo = new javax.swing.JMenuItem();
        mnuProduto = new javax.swing.JMenuItem();
        mnuEmbalagem = new javax.swing.JMenuItem();
        mnExibir = new javax.swing.JMenu();
        mnResumo = new javax.swing.JMenuItem();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setTitle("JavaLog");

        javax.swing.GroupLayout dpTelinhaLayout = new javax.swing.GroupLayout(dpTelinha);
        dpTelinha.setLayout(dpTelinhaLayout);
        dpTelinhaLayout.setHorizontalGroup(
            dpTelinhaLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 655, Short.MAX_VALUE)
        );
        dpTelinhaLayout.setVerticalGroup(
            dpTelinhaLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 505, Short.MAX_VALUE)
        );

        jMenu1.setText("Cadastrar");

        mnuVeiculo.setText("Veículos");
        mnuVeiculo.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                mnuVeiculoActionPerformed(evt);
            }
        });
        jMenu1.add(mnuVeiculo);

        mnuProduto.setText("Produtos");
        mnuProduto.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                mnuProdutoActionPerformed(evt);
            }
        });
        jMenu1.add(mnuProduto);

        mnuEmbalagem.setText("Embalagens");
        mnuEmbalagem.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                mnuEmbalagemActionPerformed(evt);
            }
        });
        jMenu1.add(mnuEmbalagem);

        jMenuBar1.add(jMenu1);

        mnExibir.setText("Exibir");

        mnResumo.setText("Resumo");
        mnResumo.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                mnResumoActionPerformed(evt);
            }
        });
        mnExibir.add(mnResumo);

        jMenuBar1.add(mnExibir);

        setJMenuBar(jMenuBar1);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(dpTelinha)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(dpTelinha)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void mnuEmbalagemActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_mnuEmbalagemActionPerformed
        var cadastrarEmbalagem  = new CadastrarEmbalagem();
        dpTelinha.add(cadastrarEmbalagem);
        cadastrarEmbalagem.setVisible(true);
        cadastrarEmbalagem.setClosable(true);
    }//GEN-LAST:event_mnuEmbalagemActionPerformed

    private void mnuProdutoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_mnuProdutoActionPerformed
        var cadastrarProduto  = new CadastrarProduto();
        dpTelinha.add(cadastrarProduto);
        cadastrarProduto.setVisible(true);
        cadastrarProduto.setClosable(true);
    }//GEN-LAST:event_mnuProdutoActionPerformed

    private void mnuVeiculoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_mnuVeiculoActionPerformed
        var cadastrarVeiculo  = new CadastrarVeiculo();
        dpTelinha.add(cadastrarVeiculo);
        cadastrarVeiculo.setVisible(true);
        cadastrarVeiculo.setClosable(true);
    }//GEN-LAST:event_mnuVeiculoActionPerformed

    private void mnResumoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_mnResumoActionPerformed
         var telaResumo  = new TelaResumo();
        dpTelinha.add(telaResumo);
        telaResumo.setVisible(true);
        telaResumo.setClosable(true);
    }//GEN-LAST:event_mnResumoActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(TelaPrincipal.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(TelaPrincipal.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(TelaPrincipal.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(TelaPrincipal.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new TelaPrincipal().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JDesktopPane dpTelinha;
    private javax.swing.JMenu jMenu1;
    private javax.swing.JMenuBar jMenuBar1;
    private javax.swing.JMenu mnExibir;
    private javax.swing.JMenuItem mnResumo;
    private javax.swing.JMenuItem mnuEmbalagem;
    private javax.swing.JMenuItem mnuProduto;
    private javax.swing.JMenuItem mnuVeiculo;
    // End of variables declaration//GEN-END:variables
}
