/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JInternalFrame.java to edit this template
 */
package sistematransportadora.ui;

import java.util.Map;
import sistematransportadora.repositorio.EmbalagemRepositorio;
import sistematransportadora.repositorio.ProdutoRepositorio;
import sistematransportadora.repositorio.VeiculoRepositorio;

/**
 *
 * @author evely
 */
public class TelaResumo extends javax.swing.JInternalFrame {

    /**
     * Creates new form TelaResumo
     */
    public TelaResumo() {
        initComponents();
        resumoProdutos(); 
        resumoEmbalagens();
        resumoVeiculos();
        
    }
    private void resumoProdutos(){
        var produtoRepositorio = new ProdutoRepositorio();
        var porTipo = produtoRepositorio.contarPorTipo();
        var quantidadeTipos = porTipo.size();
        var total = produtoRepositorio.contarTodos();
        var familiasProduto = produtoRepositorio.contarFamiliasCadastradas();
        var quantidadeLotes = produtoRepositorio.contarLotesCadastrados();
        
        StringBuilder sb = new StringBuilder();
        sb.append("Quantidade de Produtos: \n");
        
        for (Map.Entry<String, Integer> entrada : porTipo.entrySet()) {
            String chave = entrada.getKey();
            Integer valor = entrada.getValue();
            sb.append(String.format("%s = %d \n", chave, valor));
        }
        sb.append(String.format("Total = %d \n\n", total));
        sb.append(String.format("Quantidade de Tipos:\n%d \n\n", quantidadeTipos));
        sb.append(String.format("Quantidade de Famílias:\n%d \n\n", familiasProduto));
        sb.append(String.format("Quantidade de Lotes:\n%d ", quantidadeLotes));
        resumoProduto.setText(sb.toString());   
    }
    
    private void resumoEmbalagens(){
        var embalagemRepositorio = new EmbalagemRepositorio();
        var porTipo = embalagemRepositorio.contarPorTipo();
        var total = embalagemRepositorio.contarTodos();
        
        StringBuilder sb = new StringBuilder();
        sb.append("Quantidade de Embalagens: \n");
        
        for (Map.Entry<String, Integer> entrada : porTipo.entrySet()) {
            String chave = entrada.getKey();
            Integer valor = entrada.getValue();
            sb.append(String.format("%s = %d \n", chave, valor));
        }
        
        sb.append(String.format("Total = %d ", total));
        resumoEmbalagem.setText(sb.toString());  
    }
    private void resumoVeiculos(){
        var veiculoRepositorio = new VeiculoRepositorio();
        var porTipo = veiculoRepositorio.contarPorTipo();
        var total = veiculoRepositorio.contarTodos();
        
        StringBuilder sb = new StringBuilder();
        sb.append("Quantidade de Veículos: \n");
        
        for (Map.Entry<String, Integer> entrada : porTipo.entrySet()) {
            String chave = entrada.getKey();
            Integer valor = entrada.getValue();
            sb.append(String.format("%s = %d \n", chave, valor));
        }
        
        sb.append(String.format("Total = %d ", total));
        resumoVeiculo.setText(sb.toString());  
    }
    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jScrollPane1 = new javax.swing.JScrollPane();
        resumoProduto = new javax.swing.JTextArea();
        jScrollPane2 = new javax.swing.JScrollPane();
        resumoEmbalagem = new javax.swing.JTextArea();
        jScrollPane3 = new javax.swing.JScrollPane();
        resumoVeiculo = new javax.swing.JTextArea();
        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();

        setTitle("Resumo");

        resumoProduto.setEditable(false);
        resumoProduto.setColumns(20);
        resumoProduto.setRows(5);
        jScrollPane1.setViewportView(resumoProduto);

        resumoEmbalagem.setEditable(false);
        resumoEmbalagem.setColumns(20);
        resumoEmbalagem.setRows(5);
        jScrollPane2.setViewportView(resumoEmbalagem);

        resumoVeiculo.setEditable(false);
        resumoVeiculo.setColumns(20);
        resumoVeiculo.setRows(5);
        jScrollPane3.setViewportView(resumoVeiculo);

        jLabel1.setText("Contagem de Produtos:");

        jLabel2.setText("Contagem de Embalagens:");

        jLabel3.setText("Contagem de Veículos:");

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(25, 25, 25)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jScrollPane3, javax.swing.GroupLayout.PREFERRED_SIZE, 343, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel3)
                    .addComponent(jLabel2)
                    .addComponent(jLabel1)
                    .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                        .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 343, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addComponent(jScrollPane2, javax.swing.GroupLayout.PREFERRED_SIZE, 343, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addContainerGap(26, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabel1)
                .addGap(2, 2, 2)
                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jLabel2)
                .addGap(5, 5, 5)
                .addComponent(jScrollPane2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jLabel3)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jScrollPane3, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(22, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JScrollPane jScrollPane2;
    private javax.swing.JScrollPane jScrollPane3;
    private javax.swing.JTextArea resumoEmbalagem;
    private javax.swing.JTextArea resumoProduto;
    private javax.swing.JTextArea resumoVeiculo;
    // End of variables declaration//GEN-END:variables
}
