/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package sistematransportadora.ui;

import java.awt.Graphics;
import java.awt.Image;
import javax.swing.ImageIcon;

/**
 *
 * @author evely
 */
public class TelaPrincipal extends javax.swing.JFrame {

    /**
     * Creates new form telaPrincipal
     */
    public TelaPrincipal() {
        initComponents();
    }
    
    @Override
    public Image getIconImage() {
        Image img = new ImageIcon(getClass().getResource("/img/logo.png")).getImage();
        return img;
    }
    
    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        dpTelinha = new javax.swing.JDesktopPane() {
            private Image backgroundImg;
            {
                backgroundImg = new ImageIcon(getClass().getResource("/img/background.png")).getImage();
            }

            @Override
            protected void paintComponent(Graphics g) {
                super.paintComponent(g);

                int imgWidth = backgroundImg.getWidth(this);
                int imgHeight = backgroundImg.getHeight(this);
                int paneWidth = getWidth();
                int paneHeight = getHeight();

                double scaleX = (double) paneWidth / imgWidth;
                double scaleY = (double) paneHeight / imgHeight;
                double scale = Math.max(scaleX, scaleY);

                int newWidth = (int) (imgWidth * scale);
                int newHeight = (int) (imgHeight * scale);
                int x = (paneWidth - newWidth) / 2;
                int y = (paneHeight - newHeight) / 2;

                g.drawImage(backgroundImg, x, y, newWidth, newHeight, this);
            }
        };
        jMenuBar1 = new javax.swing.JMenuBar();
        jMenu1 = new javax.swing.JMenu();
        mnuVeiculo = new javax.swing.JMenuItem();
        mnuProduto = new javax.swing.JMenuItem();
        mnuEmbalagem = new javax.swing.JMenuItem();
        jSeparator2 = new javax.swing.JPopupMenu.Separator();
        mnuTipoVeiculo = new javax.swing.JMenuItem();
        mnuTipoProduto = new javax.swing.JMenuItem();
        mnuTipoEmbalagem = new javax.swing.JMenuItem();
        jSeparator3 = new javax.swing.JPopupMenu.Separator();
        mnuSair = new javax.swing.JMenuItem();
        mnExibir = new javax.swing.JMenu();
        mnuVVeiculo = new javax.swing.JMenuItem();
        mnVProduto = new javax.swing.JMenuItem();
        mnVEmbalagem = new javax.swing.JMenuItem();
        jSeparator1 = new javax.swing.JPopupMenu.Separator();
        mnResumo = new javax.swing.JMenuItem();
        mnAjuda = new javax.swing.JMenu();
        mnuSobre = new javax.swing.JMenuItem();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setTitle("JavaLog");
        setIconImage(getIconImage());

        javax.swing.GroupLayout dpTelinhaLayout = new javax.swing.GroupLayout(dpTelinha);
        dpTelinha.setLayout(dpTelinhaLayout);
        dpTelinhaLayout.setHorizontalGroup(
            dpTelinhaLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 655, Short.MAX_VALUE)
        );
        dpTelinhaLayout.setVerticalGroup(
            dpTelinhaLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 505, Short.MAX_VALUE)
        );

        jMenu1.setText("Cadastrar");

        mnuVeiculo.setText("Veículos");
        mnuVeiculo.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                mnuVeiculoActionPerformed(evt);
            }
        });
        jMenu1.add(mnuVeiculo);

        mnuProduto.setText("Produtos");
        mnuProduto.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                mnuProdutoActionPerformed(evt);
            }
        });
        jMenu1.add(mnuProduto);

        mnuEmbalagem.setText("Embalagens");
        mnuEmbalagem.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                mnuEmbalagemActionPerformed(evt);
            }
        });
        jMenu1.add(mnuEmbalagem);
        jMenu1.add(jSeparator2);

        mnuTipoVeiculo.setText("Tipo de Veículo");
        mnuTipoVeiculo.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                mnuTipoVeiculoActionPerformed(evt);
            }
        });
        jMenu1.add(mnuTipoVeiculo);

        mnuTipoProduto.setText("Tipo de Produto");
        mnuTipoProduto.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                mnuTipoProdutoActionPerformed(evt);
            }
        });
        jMenu1.add(mnuTipoProduto);

        mnuTipoEmbalagem.setText("Tipo de Embalagem");
        mnuTipoEmbalagem.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                mnuTipoEmbalagemActionPerformed(evt);
            }
        });
        jMenu1.add(mnuTipoEmbalagem);
        jMenu1.add(jSeparator3);

        mnuSair.setText("Sair");
        mnuSair.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                mnuSairActionPerformed(evt);
            }
        });
        jMenu1.add(mnuSair);

        jMenuBar1.add(jMenu1);

        mnExibir.setText("Exibir");

        mnuVVeiculo.setText("Visualizar Veículos");
        mnuVVeiculo.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                mnuVVeiculoActionPerformed(evt);
            }
        });
        mnExibir.add(mnuVVeiculo);

        mnVProduto.setText("Visualizar Produtos");
        mnVProduto.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                mnVProdutoActionPerformed(evt);
            }
        });
        mnExibir.add(mnVProduto);

        mnVEmbalagem.setText("Visualizar Embalagens");
        mnVEmbalagem.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                mnVEmbalagemActionPerformed(evt);
            }
        });
        mnExibir.add(mnVEmbalagem);
        mnExibir.add(jSeparator1);

        mnResumo.setText("Resumo");
        mnResumo.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                mnResumoActionPerformed(evt);
            }
        });
        mnExibir.add(mnResumo);

        jMenuBar1.add(mnExibir);

        mnAjuda.setText("Ajuda");

        mnuSobre.setText("Sobre");
        mnuSobre.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                mnuSobreActionPerformed(evt);
            }
        });
        mnAjuda.add(mnuSobre);

        jMenuBar1.add(mnAjuda);

        setJMenuBar(jMenuBar1);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(dpTelinha)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(dpTelinha)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void mnuEmbalagemActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_mnuEmbalagemActionPerformed
        var cadastrarEmbalagem  = new CadastrarEmbalagem();
        dpTelinha.add(cadastrarEmbalagem);
        cadastrarEmbalagem.setVisible(true);
        cadastrarEmbalagem.setClosable(true);
    }//GEN-LAST:event_mnuEmbalagemActionPerformed

    private void mnuProdutoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_mnuProdutoActionPerformed
        var cadastrarProduto  = new CadastrarProduto();
        dpTelinha.add(cadastrarProduto);
        cadastrarProduto.setVisible(true);
        cadastrarProduto.setClosable(true);
    }//GEN-LAST:event_mnuProdutoActionPerformed

    private void mnuVeiculoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_mnuVeiculoActionPerformed
        var cadastrarVeiculo  = new CadastrarVeiculo();
        dpTelinha.add(cadastrarVeiculo);
        cadastrarVeiculo.setVisible(true);
        cadastrarVeiculo.setClosable(true);
    }//GEN-LAST:event_mnuVeiculoActionPerformed

    private void mnResumoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_mnResumoActionPerformed
        var telaResumo  = new TelaResumo();
        dpTelinha.add(telaResumo);
        telaResumo.setVisible(true);
        telaResumo.setClosable(true);
    }//GEN-LAST:event_mnResumoActionPerformed

    private void mnuVVeiculoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_mnuVVeiculoActionPerformed
        var visualizacaoVeiculo  = new VisualizacaoVeiculo();
        dpTelinha.add(visualizacaoVeiculo);
        visualizacaoVeiculo.setVisible(true);
        visualizacaoVeiculo.setClosable(true);
    }//GEN-LAST:event_mnuVVeiculoActionPerformed

    private void mnVProdutoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_mnVProdutoActionPerformed
       var visualizacaoProduto  = new VisualizacaoProduto();
        dpTelinha.add(visualizacaoProduto);
        visualizacaoProduto.setVisible(true);
        visualizacaoProduto.setClosable(true);
    }//GEN-LAST:event_mnVProdutoActionPerformed

    private void mnVEmbalagemActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_mnVEmbalagemActionPerformed
        var visualizacaoEmbalagem  = new VisualizacaoEmbalagem();
        dpTelinha.add(visualizacaoEmbalagem);
        visualizacaoEmbalagem.setVisible(true);
        visualizacaoEmbalagem.setClosable(true);
    }//GEN-LAST:event_mnVEmbalagemActionPerformed

    private void mnuTipoProdutoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_mnuTipoProdutoActionPerformed
        var cadastroTipoProduto = new CadastrarTipoProduto();
        dpTelinha.add(cadastroTipoProduto);
        cadastroTipoProduto.setVisible(true);
        cadastroTipoProduto.setClosable(true);
    }//GEN-LAST:event_mnuTipoProdutoActionPerformed

    private void mnuTipoVeiculoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_mnuTipoVeiculoActionPerformed
        var cadastroTipoVeiculo = new CadastrarTipoVeiculo();
        dpTelinha.add(cadastroTipoVeiculo);
        cadastroTipoVeiculo.setVisible(true);
        cadastroTipoVeiculo.setClosable(true);
    }//GEN-LAST:event_mnuTipoVeiculoActionPerformed

    private void mnuTipoEmbalagemActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_mnuTipoEmbalagemActionPerformed
        var cadastroTipoEmbalagem = new CadastrarTipoEmbalagem();
        dpTelinha.add(cadastroTipoEmbalagem);
        cadastroTipoEmbalagem.setVisible(true);
        cadastroTipoEmbalagem.setClosable(true);
    }//GEN-LAST:event_mnuTipoEmbalagemActionPerformed

    private void mnuSairActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_mnuSairActionPerformed
        System.exit(0);
    }//GEN-LAST:event_mnuSairActionPerformed

    private void mnuSobreActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_mnuSobreActionPerformed
        var sobre = new TelaSobre();
        dpTelinha.add(sobre);
        sobre.setVisible(true);
        sobre.setClosable(true);
    }//GEN-LAST:event_mnuSobreActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(TelaPrincipal.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(TelaPrincipal.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(TelaPrincipal.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(TelaPrincipal.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new TelaPrincipal().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JDesktopPane dpTelinha;
    private javax.swing.JMenu jMenu1;
    private javax.swing.JMenuBar jMenuBar1;
    private javax.swing.JPopupMenu.Separator jSeparator1;
    private javax.swing.JPopupMenu.Separator jSeparator2;
    private javax.swing.JPopupMenu.Separator jSeparator3;
    private javax.swing.JMenu mnAjuda;
    private javax.swing.JMenu mnExibir;
    private javax.swing.JMenuItem mnResumo;
    private javax.swing.JMenuItem mnVEmbalagem;
    private javax.swing.JMenuItem mnVProduto;
    private javax.swing.JMenuItem mnuEmbalagem;
    private javax.swing.JMenuItem mnuProduto;
    private javax.swing.JMenuItem mnuSair;
    private javax.swing.JMenuItem mnuSobre;
    private javax.swing.JMenuItem mnuTipoEmbalagem;
    private javax.swing.JMenuItem mnuTipoProduto;
    private javax.swing.JMenuItem mnuTipoVeiculo;
    private javax.swing.JMenuItem mnuVVeiculo;
    private javax.swing.JMenuItem mnuVeiculo;
    // End of variables declaration//GEN-END:variables
}
