/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JInternalFrame.java to edit this template
 */
package sistematransportadora.ui;

import sistematransportadora.SistemaTransportadora;

import java.awt.Desktop;
import java.awt.Image;
import javax.swing.ImageIcon;

/**
 *
 * @author pedro
 */
public class TelaSobre extends javax.swing.JInternalFrame {

    /**
     * Creates new form TelaSobre
     */
    public TelaSobre() {
        initComponents();
        carregarImagem();
    }

    private void carregarImagem() {
        imageLabel.setText("");
        var iconImage = new ImageIcon(getClass().getResource("/img/text-logo.png"));
        var img = iconImage.getImage().getScaledInstance(350, 89, Image.SCALE_SMOOTH);
        imageLabel.setIcon(new ImageIcon(img));
        versaoLabel.setText(String.format(
            "Versão: %s", SistemaTransportadora.VERSAO_APP
        ));
    }
    
    private void abrirUrl(String url) {
        if (Desktop.isDesktopSupported()) {
            try {
                Desktop.getDesktop().browse(new java.net.URI(url));
            } catch (Exception e) {
                System.out.println("Erro ao abrir link: " + e.getMessage());
            }
        }
    }
    
    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        imageLabel = new javax.swing.JLabel();
        versaoLabel = new javax.swing.JLabel();
        jLabel1 = new javax.swing.JLabel();
        lblPedro = new javax.swing.JLabel();
        lblEvelyn = new javax.swing.JLabel();

        setTitle("Sobre a aplicação");

        imageLabel.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        imageLabel.setText("Visualização da Logo com Texto");

        versaoLabel.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        versaoLabel.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        versaoLabel.setText("Versão: v0.0.0");

        jLabel1.setText("Trabalho escolar do CEFET/RJ Uned Nova Iguaçu realizado por:");

        lblPedro.setForeground(new java.awt.Color(51, 102, 255));
        lblPedro.setText("<html><u>Pedro Anuda</u></html>");
        lblPedro.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                lblPedroMouseClicked(evt);
            }
        });

        lblEvelyn.setForeground(new java.awt.Color(51, 102, 255));
        lblEvelyn.setText("<html><u>Evelyn Motta</u></html>");
        lblEvelyn.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                lblEvelynMouseClicked(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(24, 24, 24)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(lblEvelyn, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(lblPedro, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel1)
                    .addComponent(versaoLabel, javax.swing.GroupLayout.PREFERRED_SIZE, 351, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(imageLabel, javax.swing.GroupLayout.PREFERRED_SIZE, 351, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap(23, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(imageLabel, javax.swing.GroupLayout.PREFERRED_SIZE, 102, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(versaoLabel)
                .addGap(32, 32, 32)
                .addComponent(jLabel1)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(lblPedro, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(lblEvelyn, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(24, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void lblPedroMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_lblPedroMouseClicked
        abrirUrl("https://github.com/pedroanuda");
    }//GEN-LAST:event_lblPedroMouseClicked

    private void lblEvelynMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_lblEvelynMouseClicked
        abrirUrl("https://github.com/EvelynMotta");
    }//GEN-LAST:event_lblEvelynMouseClicked


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel imageLabel;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel lblEvelyn;
    private javax.swing.JLabel lblPedro;
    private javax.swing.JLabel versaoLabel;
    // End of variables declaration//GEN-END:variables
}
