/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JInternalFrame.java to edit this template
 */
package sistematransportadora.ui;

import javax.swing.JOptionPane;
import javax.swing.table.DefaultTableModel;
import sistematransportadora.servico.ProdutoServico;

/**
 *
 * @author evely
 */
public class VisualizacaoProduto extends javax.swing.JInternalFrame {
    private final ProdutoServico produtoServico;
    private DefaultTableModel modeloTabela;
    /**
     * Creates new form VisualizacaoProduto
     */
    public VisualizacaoProduto() {
        produtoServico = new ProdutoServico();
        initComponents();
        criarModelo();
    }
     public DefaultTableModel getModeloTabela() {
        return modeloTabela;
    }
    
    private void criarModelo(){
        modeloTabela = new DefaultTableModel() {
            @Override
            public boolean isCellEditable(int row, int column) {
                return false;
            }
        };
        modeloTabela.addColumn("Id");
        modeloTabela.addColumn("Nome");
        modeloTabela.addColumn("Descrição");
        modeloTabela.addColumn("Família");
        modeloTabela.addColumn("Tipo");
        modeloTabela.addColumn("Lote");
        modeloTabela.addColumn("Altura");
        modeloTabela.addColumn("Largura");
        modeloTabela.addColumn("Comprimento");
        modeloTabela.addColumn("Peso");
        modeloTabela.addColumn("Grau de Fragilidade");
        modeloTabela.addColumn("Observações");
        
        for(var produto : produtoServico.buscarTodos()){
            var fragilidade = switch (produto.getGrauFragilidade()) {
              case ALTA -> "Alta";
              case MEDIA -> "Média";
              default -> "Baixa";
            };
            
            modeloTabela.addRow(new Object[] {
                produto.getId(),
                produto.getNome(),
                produto.getDescricao(),
                produto.getFamilia(),
                produto.getTipo().nome(),
                produto.getLote(),
                produto.getDimensoes().altura,
                produto.getDimensoes().largura,
                produto.getDimensoes().comprimento,
                produto.getPeso(),
                fragilidade,
                produto.getObservacoes()
            });
        }
        tProdutos.setModel(modeloTabela);
        tProdutos.getColumn("Observações").setMinWidth(200);
        tProdutos.getColumn("Descrição").setMinWidth(200);
    }
    
 private void Apagar(){
        var linha = tProdutos.getSelectedRow();
        
        if(linha == -1) {
            JOptionPane.showMessageDialog(
                    null, "Não há nenhum produto selecionado",
                    "Erro!", JOptionPane.ERROR_MESSAGE
            );
            return;
        }
        
        try {
            var id = (int)tProdutos.getValueAt(linha, 0); 
            modeloTabela.removeRow(linha);
            produtoServico.excluirProduto(id);
        } catch (Exception e) {
            JOptionPane.showMessageDialog(
                    null, e.getMessage(),
                    "Erro!", JOptionPane.ERROR_MESSAGE
            );
        }
    }
    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jScrollPane1 = new javax.swing.JScrollPane();
        tProdutos = new javax.swing.JTable();
        bntApagar = new javax.swing.JButton();

        setTitle("Visualização Produtos");
        setVisible(true);

        tProdutos.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null}
            },
            new String [] {
                "Title 1", "Title 2", "Title 3", "Title 4"
            }
        ));
        tProdutos.setAutoResizeMode(javax.swing.JTable.AUTO_RESIZE_OFF);
        tProdutos.setSelectionMode(javax.swing.ListSelectionModel.SINGLE_SELECTION);
        jScrollPane1.setViewportView(tProdutos);

        bntApagar.setText("Apagar");
        bntApagar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                bntApagarActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(6, 6, 6)
                        .addComponent(bntApagar)
                        .addContainerGap(329, Short.MAX_VALUE))
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 0, Short.MAX_VALUE)
                        .addContainerGap())))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 166, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(bntApagar)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void bntApagarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_bntApagarActionPerformed
       Apagar();
    }//GEN-LAST:event_bntApagarActionPerformed


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton bntApagar;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JTable tProdutos;
    // End of variables declaration//GEN-END:variables
}
