/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JInternalFrame.java to edit this template
 */
package sistematransportadora.ui;

import javax.swing.JOptionPane;
import javax.swing.table.DefaultTableModel;
import sistematransportadora.servico.VeiculoServico;

/**
 *
 * @author evely
 */
public class VisualizacaoVeiculo extends javax.swing.JInternalFrame {
    private final VeiculoServico veiculoServico;
    private DefaultTableModel modeloTabela; 
    /**
     * Creates new form VisualizacaoVeiculo
     */
    public VisualizacaoVeiculo() {
        veiculoServico = new VeiculoServico();
        initComponents();
        criarModelo();
    }

    public DefaultTableModel getModeloTabela() {
        return modeloTabela;
    }
    
    private void criarModelo(){
        modeloTabela = new DefaultTableModel() {
            @Override
            public boolean isCellEditable(int row, int column) {
                return false;
            }
        };
        modeloTabela.addColumn("Id");
        modeloTabela.addColumn("Placa");
        modeloTabela.addColumn("Nome");
        modeloTabela.addColumn("Modelo");
        modeloTabela.addColumn("Tipo"); 
        modeloTabela.addColumn("Largura Interna");
        modeloTabela.addColumn("Altura Interna");
        modeloTabela.addColumn("Comprimento Interno");
        modeloTabela.addColumn("Capacidade de Peso");
        modeloTabela.addColumn("Observações");
        
        for(var veiculo : veiculoServico.buscarTodos()){
            modeloTabela.addRow(new Object[] {
                veiculo.getId(),
                veiculo.getPlaca(),
                veiculo.getNome(),
                veiculo.getModelo(),
                veiculo.getTipo().nome(),
                veiculo.getDimensoesInternas().largura,
                veiculo.getDimensoesInternas().altura,
                veiculo.getDimensoesInternas().comprimento,
                veiculo.getCapacidadeDePeso(),
                veiculo.getObservacoes()
            });
        }
        jTabela.setModel(modeloTabela);
        jTabela.getColumn("Observações").setMinWidth(200);
    }
    
    private void Apagar(){
        var linha = jTabela.getSelectedRow();
        
        if(linha == -1) {
            JOptionPane.showMessageDialog(
                    null, "Não há nenhum veículo selecionado",
                    "Erro!", JOptionPane.ERROR_MESSAGE
            );
            return;
        }
        
        try {
            var id = (int)jTabela.getValueAt(linha, 0); 
            modeloTabela.removeRow(linha);
            veiculoServico.excluirVeiculo(id);
        } catch (Exception e) {
            JOptionPane.showMessageDialog(
                    null, e.getMessage(),
                    "Erro!", JOptionPane.ERROR_MESSAGE
            );
        }
    }
    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        btnApagar = new javax.swing.JButton();
        jScrollPane1 = new javax.swing.JScrollPane();
        jTabela = new javax.swing.JTable();

        setTitle("Visualização Veículo");

        btnApagar.setText("Apagar");
        btnApagar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnApagarActionPerformed(evt);
            }
        });

        jScrollPane1.setHorizontalScrollBarPolicy(javax.swing.ScrollPaneConstants.HORIZONTAL_SCROLLBAR_ALWAYS);
        jScrollPane1.setToolTipText("");

        jTabela.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null}
            },
            new String [] {
                "Title 1", "Title 2", "Title 3", "Title 4"
            }
        ));
        jTabela.setAutoResizeMode(javax.swing.JTable.AUTO_RESIZE_OFF);
        jTabela.setSelectionMode(javax.swing.ListSelectionModel.SINGLE_SELECTION);
        jScrollPane1.setViewportView(jTabela);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 404, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(btnApagar))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 173, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(btnApagar)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void btnApagarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnApagarActionPerformed
        Apagar();
    }//GEN-LAST:event_btnApagarActionPerformed


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnApagar;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JTable jTabela;
    // End of variables declaration//GEN-END:variables
}
