/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JInternalFrame.java to edit this template
 */
package sistematransportadora.ui;

import javax.swing.JOptionPane;
import javax.swing.table.DefaultTableModel;
import sistematransportadora.servico.EmbalagemServico;

/**
 *
 * @author evely
 */
public class VisualizacaoEmbalagem extends javax.swing.JInternalFrame {
    private final EmbalagemServico embalagemServico;
    private DefaultTableModel modeloTabela;
    /**
     * Creates new form VisualizacaoEmbalagem
     */
    public VisualizacaoEmbalagem() {
        embalagemServico = new EmbalagemServico();
        initComponents();
        criarModelo();
    }
    public DefaultTableModel getModeloTabela() {
        return modeloTabela;
    }
    
    private void criarModelo(){
        modeloTabela = new DefaultTableModel() {
            @Override
            public boolean isCellEditable(int row, int column) {
                return false;
            }
        };
        modeloTabela.addColumn("Id");
        modeloTabela.addColumn("Tipo");
        modeloTabela.addColumn("Produto Associado");
        modeloTabela.addColumn("Altura");
        modeloTabela.addColumn("Largura");
        modeloTabela.addColumn("Comprimento");
        modeloTabela.addColumn("Peso");
        modeloTabela.addColumn("Empilhável");
        modeloTabela.addColumn("Observações");
        
        for(var embalagem : embalagemServico.buscarTodas()){
            var produto = embalagem.getProdutoAssociado();
            var empilhavel = embalagem.isEmpilhavel();
            
            modeloTabela.addRow(new Object[] {
                embalagem.getId(),
                embalagem.getTipo().nome(),
                produto != null ? produto.getNome() : "N/A",
                embalagem.getDimensoes().altura,
                embalagem.getDimensoes().largura,
                embalagem.getDimensoes().comprimento,
                embalagem.getPeso(),
                empilhavel ? "Sim" : "Não",
                embalagem.getObservacoes()
            });
        }
         tEmbalagem.setModel(modeloTabela);
         tEmbalagem.getColumn("Observações").setMinWidth(200);   
    }
    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jScrollPane1 = new javax.swing.JScrollPane();
        tEmbalagem = new javax.swing.JTable();
        btnApagar = new javax.swing.JButton();

        setTitle("Visualização Embalagens");

        tEmbalagem.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null}
            },
            new String [] {
                "Title 1", "Title 2", "Title 3", "Title 4"
            }
        ));
        tEmbalagem.setAutoResizeMode(javax.swing.JTable.AUTO_RESIZE_OFF);
        tEmbalagem.setSelectionMode(javax.swing.ListSelectionModel.SINGLE_SELECTION);
        jScrollPane1.setViewportView(tEmbalagem);

        btnApagar.setText("Apagar");
        btnApagar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnApagarActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(6, 6, 6)
                        .addComponent(btnApagar)
                        .addContainerGap(317, Short.MAX_VALUE))
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 0, Short.MAX_VALUE)
                        .addContainerGap())))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 174, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(btnApagar)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents
private void Apagar(){
        var linha = tEmbalagem.getSelectedRow();
        
        if(linha == -1) {
            JOptionPane.showMessageDialog(
                    null, "Não há nenhuma embalagem selecionada",
                    "Erro!", JOptionPane.ERROR_MESSAGE
            );
            return;
        }
        
        try {
            var id = (int)tEmbalagem.getValueAt(linha, 0); 
            modeloTabela.removeRow(linha);
            embalagemServico.excluirEmbalagem(id);
        } catch (Exception e) {
            JOptionPane.showMessageDialog(
                    null, e.getMessage(),
                    "Erro!", JOptionPane.ERROR_MESSAGE
            );
        }
    }
    private void btnApagarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnApagarActionPerformed
       Apagar();
    }//GEN-LAST:event_btnApagarActionPerformed


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnApagar;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JTable tEmbalagem;
    // End of variables declaration//GEN-END:variables
}
